#ifndef QFTPSERVERLIB_GLOBAL_H
#define QFTPSERVERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QFTPSERVERLIB_LIBRARY)
#  define QFTPSERVERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QFTPSERVERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#define BEGIN_FTP_NAMESPACE namespace Ftp{
#define END_FTP_NAMESPACE }


#endif // QFTPSERVERLIB_GLOBAL_H
